INSERT INTO city (name) VALUES ('Kraków');
INSERT INTO city (name) VALUES ('Warszawa');
INSERT INTO city (name) VALUES ('Wrocław');
INSERT INTO city (name) VALUES ('Poznań');
INSERT INTO city (name) VALUES ('Łódź');
INSERT INTO city (name) VALUES ('Szczecin');
INSERT INTO city (name) VALUES ('Gdańsk');
INSERT INTO city (name) VALUES ('Katowice');
INSERT INTO city (name) VALUES ('Rzeszów');
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Jagielloński', 1);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny w Krakowie', 1);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Rolniczy', 1);
INSERT INTO university (name, city_id) VALUES ('Politechnika Krakowska', 1);
INSERT INTO university (name, city_id) VALUES ('Akademia Górniczo-Hutnicza', 1);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Warszawski', 2);
INSERT INTO university (name, city_id) VALUES ('Politechnika Warszawska', 2);
INSERT INTO university (name, city_id) VALUES ('Szkoła Główna Handlowa', 2);
INSERT INTO university (name, city_id) VALUES ('Dolnośląska Szkoła Wyższa', 3);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny we Wrocławiu', 3);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Wrocławski', 3);
INSERT INTO university (name, city_id) VALUES ('Wyższa Szkoła Informatyki Stosowanej', 3);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet im. Adama Mickiewicza w Poznaniu', 4);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny w Poznaniu', 4);
INSERT INTO university (name, city_id) VALUES ('Politechnika Poznańska', 4);
INSERT INTO university (name, city_id) VALUES ('Politechnika Łódzka', 5);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Łódzki', 5);
INSERT INTO university (name, city_id) VALUES ('Szkoła Wyższa Ekonomii i Zarządzania w Łodzi', 5);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Szczeciński', 6);
INSERT INTO university (name, city_id) VALUES ('Akademia Morska w Szczecinie', 6);
INSERT INTO university (name, city_id) VALUES ('Wyższa Szkoła Administracji Publicznej w Szczecinie', 6);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Gdański', 7);
INSERT INTO university (name, city_id) VALUES ('Politechnika Gdańska', 7);
INSERT INTO university (name, city_id) VALUES ('ATENEUM Szkoła Wyższa w Gdańsku', 7);
INSERT INTO university (name, city_id) VALUES ('Wyższa Szkoła Bankowa w Gdańsku', 7);
INSERT INTO university (name, city_id) VALUES ('Górnośląska Wyższa Szkoła Handlowa', 8);
INSERT INTO university (name, city_id) VALUES ('Śląska Wyższa Szkoła Informatyczno-Medyczna', 8);
INSERT INTO university (name, city_id) VALUES ('Śląska Wyższa Szkoła Zarządzania', 8);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny w Katowicach', 8);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Śląski', 8);
INSERT INTO university (name, city_id) VALUES ('Wyższa Szkoła Techniczna', 8);
INSERT INTO university (name, city_id) VALUES ('Wyższa Szkoła Technologii Informatycznych', 8);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Rzeszowski', 9);
INSERT INTO university (name, city_id) VALUES ('Wyższa Szkoła Informatyki i Zarządzania', 9);
INSERT INTO university (name, city_id) VALUES ('Politechnika Rzeszowska', 9);