INSERT INTO city (name) VALUES ('Krakow');
INSERT INTO city (name) VALUES ('Warszawa');
INSERT INTO city (name) VALUES ('Wroclaw');
INSERT INTO city (name) VALUES ('Poznań');
INSERT INTO city (name) VALUES ('Lodz');
INSERT INTO city (name) VALUES ('Szczecin');
INSERT INTO city (name) VALUES ('Gdańsk');
INSERT INTO city (name) VALUES ('Katowice');
INSERT INTO city (name) VALUES ('Rzeszow');
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Jagiellonski', 1);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny w Krakowie', 1);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Rolniczy', 1);
INSERT INTO university (name, city_id) VALUES ('Politechnika Krakowska', 1);
INSERT INTO university (name, city_id) VALUES ('Akademia Gorniczo-Hutnicza', 1);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Warszawski', 2);
INSERT INTO university (name, city_id) VALUES ('Politechnika Warszawska', 2);
INSERT INTO university (name, city_id) VALUES ('Szkoła Głowna Handlowa', 2);
INSERT INTO university (name, city_id) VALUES ('Dolnoslaska Szkola Wyzsza', 3);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny we Wroclawiu', 3);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Wroclawski', 3);
INSERT INTO university (name, city_id) VALUES ('Wyzsza Szkola Informatyki Stosowanej', 3);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet im. Adama Mickiewicza w Poznaniu', 4);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny w Poznaniu', 4);
INSERT INTO university (name, city_id) VALUES ('Politechnika Poznanska', 4);
INSERT INTO university (name, city_id) VALUES ('Politechnika Łodzka', 5);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Łodzki', 5);
INSERT INTO university (name, city_id) VALUES ('Szkola Wyzsza Ekonomii i Zarzadzania w Lodzi', 5);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Szczecinski', 6);
INSERT INTO university (name, city_id) VALUES ('Akademia Morska w Szczecinie', 6);
INSERT INTO university (name, city_id) VALUES ('Wyzsza Szkola Administracji Publicznej w Szczecinie', 6);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Gdanski', 7);
INSERT INTO university (name, city_id) VALUES ('Politechnika Gdanska', 7);
INSERT INTO university (name, city_id) VALUES ('ATENEUM Szkola Wyzsza w Gdansku', 7);
INSERT INTO university (name, city_id) VALUES ('Wyzsza Szkola Bankowa w Gdansku', 7);
INSERT INTO university (name, city_id) VALUES ('Gornoślaska Wyzsza Szkola Handlowa', 8);
INSERT INTO university (name, city_id) VALUES ('Slaska Wyzsza Szkola Informatyczno-Medyczna', 8);
INSERT INTO university (name, city_id) VALUES ('Slaska Wyzsza Szkola Zarzadzania', 8);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Ekonomiczny w Katowicach', 8);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Slaski', 8);
INSERT INTO university (name, city_id) VALUES ('Wyzsza Szkola Techniczna', 8);
INSERT INTO university (name, city_id) VALUES ('Wyzsza Szkola Technologii Informatycznych', 8);
INSERT INTO university (name, city_id) VALUES ('Uniwersytet Rzeszowski', 9);
INSERT INTO university (name, city_id) VALUES ('Wyzsza Szkola Informatyki i Zarzadzania', 9);
INSERT INTO university (name, city_id) VALUES ('Politechnika Rzeszowska', 9);